import 'package:chem_x/Controller/single_element_data.dart';
import 'package:chem_x/View/element_tile.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'dart:convert';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class PeriodicTable extends StatefulWidget {
  PeriodicTable({Key? key}) : super(key: key);
  final periodicList = rootBundle
      .loadString("assets/data/elementsData.json")
      .then((value) => jsonDecode(value)['myelements'] as List)
      .then((list) => list
      .map((json) => json != null ? Autogenerated.fromJson(json) : null)
      .toList());
  @override
  _PeriodicTableState createState() => _PeriodicTableState();
}

class _PeriodicTableState extends State<PeriodicTable> {

  _buildTable(List<Autogenerated?> elements) {
    final forGrid = elements
        .map(
          (element) => elements != null
              ? ElementTile(element: element!)
              : Container(
                  margin: EdgeInsets.all(1.w),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(10),
                  ),
                ),
        )
        .toList();
    return SingleChildScrollView(
      child: SizedBox(
        height: 100,
        child: GridView.count(
          crossAxisCount: 10,
          children: <Widget>[...forGrid],
        ),
      ),
    );

  }

  @override
  Widget build(BuildContext context) {

    return FutureBuilder(
      future: widget.periodicList,
      builder: (_, AsyncSnapshot snapshot) => snapshot.hasData
          ? _buildTable(snapshot.data)
          : const Center(
              child: CircularProgressIndicator(),
            ),
    );
  }
}
