import 'dart:convert';
import 'dart:io';

class Autogenerated {
  List<Myelements>? myelements;

  Autogenerated({this.myelements});
  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['myelements'] != null) {
      myelements = <Myelements>[];
      json['myelements'].forEach((v) {
        myelements!.add(Myelements.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (myelements != null) {
      data['myelements'] = myelements!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Myelements {
  String? name;
  String? appearance;
  double? atomicMass;
  double? boil;
  String? category;
  double? density;
  String? discoveredBy;
  double? melt;
  double? molarHeat;
  String? namedBy;
  int? number;
  int? period;
  String? phase;
  String? source;
  String? bohrModelImage;
  String? bohrModel3d;
  String? spectralImg;
  String? summary;
  String? symbol;
  int? xpos;
  int? ypos;
  List<int>? shells;
  String? electronConfiguration;
  String? electronConfigurationSemantic;
  double? electronAffinity;
  double? electronegativityPauling;
  List<int>? ionizationEnergies;
  String? cpkHex;
  Image? image;

  Myelements(
      {this.name,
      this.appearance,
      this.atomicMass,
      this.boil,
      this.category,
      this.density,
      this.discoveredBy,
      this.melt,
      this.molarHeat,
      this.namedBy,
      this.number,
      this.period,
      this.phase,
      this.source,
      this.bohrModelImage,
      this.bohrModel3d,
      this.spectralImg,
      this.summary,
      this.symbol,
      this.xpos,
      this.ypos,
      this.shells,
      this.electronConfiguration,
      this.electronConfigurationSemantic,
      this.electronAffinity,
      this.electronegativityPauling,
      this.ionizationEnergies,
      this.cpkHex,
      this.image});

  Myelements.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    appearance = json['appearance'];
    atomicMass = json['atomic_mass'];
    boil = json['boil'];
    category = json['category'];
    density = json['density'];
    discoveredBy = json['discovered_by'];
    melt = json['melt'];
    molarHeat = json['molar_heat'];
    namedBy = json['named_by'];
    number = json['number'];
    period = json['period'];
    phase = json['phase'];
    source = json['source'];
    bohrModelImage = json['bohr_model_image'];
    bohrModel3d = json['bohr_model_3d'];
    spectralImg = json['spectral_img'];
    summary = json['summary'];
    symbol = json['symbol'];
    xpos = json['xpos'];
    ypos = json['ypos'];
    shells = json['shells'].cast<int>();
    electronConfiguration = json['electron_configuration'];
    electronConfigurationSemantic = json['electron_configuration_semantic'];
    electronAffinity = json['electron_affinity'];
    electronegativityPauling = json['electronegativity_pauling'];
    ionizationEnergies = json['ionization_energies'].cast<int>();
    cpkHex = json['cpk-hex'];
    image = json['image'] != null ? Image.fromJson(json['image']) : null;
  }

  static Future<void> addNewQuiz(String newName, String newSummary) async {
    var jsonNewQuizObject = {'name': newName, 'summary': newSummary};
    String jsonNewQuizString = jsonEncode(jsonNewQuizObject);
    await File("assets/data/quizzesData.json").writeAsString(jsonNewQuizString);
    print("*****************************");
    print(jsonNewQuizString);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['name'] = name;
    data['appearance'] = appearance;
    data['atomic_mass'] = atomicMass;
    data['boil'] = boil;
    data['category'] = category;
    data['density'] = density;
    data['discovered_by'] = discoveredBy;
    data['melt'] = melt;
    data['molar_heat'] = molarHeat;
    data['named_by'] = namedBy;
    data['number'] = number;
    data['period'] = period;
    data['phase'] = phase;
    data['source'] = source;
    data['bohr_model_image'] = bohrModelImage;
    data['bohr_model_3d'] = bohrModel3d;
    data['spectral_img'] = spectralImg;
    data['summary'] = summary;
    data['symbol'] = symbol;
    data['xpos'] = xpos;
    data['ypos'] = ypos;
    data['shells'] = shells;
    data['electron_configuration'] = electronConfiguration;
    data['electron_configuration_semantic'] = electronConfigurationSemantic;
    data['electron_affinity'] = electronAffinity;
    data['electronegativity_pauling'] = electronegativityPauling;
    data['ionization_energies'] = ionizationEnergies;
    data['cpk-hex'] = cpkHex;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    return data;
  }
}


class Image {
  String? title;
  String? url;
  String? attribution;

  Image({this.title, this.url, this.attribution});

  Image.fromJson(Map<String, dynamic> json) {
    title = json['title'];
    url = json['url'];
    attribution = json['attribution'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['title'] = title;
    data['url'] = url;
    data['attribution'] = attribution;
    return data;
  }
}